### ISSUE TITLE
Virtuemart - Logo

### ISSUE THREAD

**Issue by laruzzo** [bitpay/oscommerce-plugin#35]
Hi, I woud like to add a logo for Bitpay payment plugin for Virtuemart. This is the only payment plugin that there are no place to add a logo in configuration menu. Tks.

**Comment by kleetus** [comment]
Is this a logo that would be stored in this repository?

**Comment by laruzzo** [comment]
I would like to have Bitcoin logo inside virtuemart. A custom logo uploaded into my host. When my customer goes to the cart in my site store there are many payment options. All the Virtuemart payments plugins has a logo and this logo is displayed in cart to customer.

**Comment by laruzzo** [comment]
Bitpay has no logo. And display only the name of payment method: "Bitpay". Instead of a logo image.

**Comment by laruzzo** [comment]
http://docs.virtuemart.net/tutorials/templating-layouts/79-logo-for-payment-and-shipment.html

**Comment by kleetus** [comment]
I am bit lost, what do Virutemart Logos have to do with oscommerce or the BitPay oscommerce plugin? Should this issue be here?  https://github.com/bitpay/virtuemart-plugin

**Comment by laruzzo** [comment]
My mistake. sorry. I thought was in the virtuemart section. Tks
